# Generated by Django 2.2.2 on 2019-07-16 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('invest', models.CharField(max_length=1000)),
                ('remark', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('period', models.CharField(max_length=1000)),
                ('coordinator', models.CharField(max_length=1000)),
                ('remark', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('sponsor', models.CharField(max_length=1000)),
                ('organizer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('lab', models.CharField(default='', max_length=1000)),
                ('grant', models.CharField(default='', max_length=1000)),
                ('year', models.CharField(default='', max_length=1000)),
                ('scope', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COI', models.ManyToManyField(to='Run.Certify')),
                ('collab', models.ManyToManyField(to='Run.Collab')),
                ('conferences', models.ManyToManyField(to='Run.Conferences')),
                ('labo', models.ManyToManyField(to='Run.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('speaker', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=1000)),
                ('date', models.DateField(null=True)),
                ('remark', models.TextField(default='')),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro1', to='Run.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Research2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('authority', models.CharField(default='', max_length=1000)),
                ('period', models.CharField(default='', max_length=1000)),
                ('grant', models.CharField(default='', max_length=1000)),
                ('order', models.CharField(default='', max_length=1000)),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro6', to='Run.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Research1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='', max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('authority', models.CharField(default='', max_length=1000)),
                ('period', models.CharField(default='', max_length=1000)),
                ('grant', models.CharField(default='', max_length=1000)),
                ('order', models.CharField(default='', max_length=1000)),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro5', to='Run.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='research1',
            field=models.ManyToManyField(to='Run.Research1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research2',
            field=models.ManyToManyField(to='Run.Research2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='webinars',
            field=models.ManyToManyField(to='Run.Webinars'),
        ),
        migrations.AddField(
            model_name='industry',
            name='profile1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro4', to='Run.Profile'),
        ),
        migrations.AddField(
            model_name='conferences',
            name='profile1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='Run.Profile'),
        ),
        migrations.AddField(
            model_name='collab',
            name='profile1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro2', to='Run.Profile'),
        ),
        migrations.AddField(
            model_name='certify',
            name='profile1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro3', to='Run.Profile'),
        ),
    ]
