# Generated by Django 2.2.2 on 2019-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='research1',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='research2',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
