# Generated by Django 2.2.2 on 2019-07-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0002_conferences_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('speaker', models.CharField(max_length=1000)),
                ('number', models.CharField(max_length=1000)),
                ('remarks', models.TextField()),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro1', to='Run.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='webinars',
            field=models.ManyToManyField(to='Run.Webinars'),
        ),
    ]
