# Generated by Django 2.2.2 on 2019-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0002_auto_20190716_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
