# Generated by Django 2.2.2 on 2019-07-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0004_auto_20190715_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('period', models.CharField(max_length=1000)),
                ('coodinator', models.CharField(max_length=1000)),
                ('remarks', models.TextField()),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro2', to='Run.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='collab',
            field=models.ManyToManyField(to='Run.Collab'),
        ),
    ]
