# Generated by Django 2.2.2 on 2019-07-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0005_auto_20190715_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collab',
            old_name='coodinator',
            new_name='coordinator',
        ),
    ]
