# Generated by Django 2.2.2 on 2019-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0006_auto_20190715_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collab',
            name='remarks',
        ),
        migrations.AddField(
            model_name='collab',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
