# Generated by Django 2.2.2 on 2019-07-15 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0007_auto_20190715_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('invest', models.CharField(max_length=1000)),
                ('remarks', models.TextField(default='')),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro3', to='Run.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='COI',
            field=models.ManyToManyField(to='Run.Certify'),
        ),
    ]
