# Generated by Django 2.2.2 on 2019-07-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0008_auto_20190715_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certify',
            old_name='remarks',
            new_name='remark',
        ),
    ]
