# Generated by Django 2.2.2 on 2019-07-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Run', '0009_auto_20190715_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=1000)),
                ('lab', models.CharField(default='', max_length=1000)),
                ('grant', models.CharField(default='', max_length=1000)),
                ('year', models.CharField(default='', max_length=1000)),
                ('scope', models.TextField(default='')),
                ('profile1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro4', to='Run.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='labo',
            field=models.ManyToManyField(to='Run.Industry'),
        ),
    ]
